# syntax = docker/dockerfile:1.2

FROM osgeo/gdal:ubuntu-full-3.6.3
# This image is built on "Ubuntu 22.04.2 LTS"

# remove reference to missing repo
RUN rm /etc/apt/sources.list.d/apache-arrow.sources

# Install the required Python packages.
RUN apt-get update && apt-get install -y \
    libmecab-dev \
    mecab-ipadic-utf8 \
    libboost-all-dev \
    libsqlite3-dev \
    curl \
    python3 \
    python3-dev \
    python3-pip

# Setup application
RUN mkdir /develop
COPY setup.py README.md /develop/
COPY base_data/ /develop/base_data/
COPY libgeonlp/ /develop/libgeonlp/
COPY pygeonlp/ /develop/pygeonlp/

WORKDIR /develop
RUN --mount=type=cache,target=/root/.cache/pip \
    python3 -m pip install -e . && pygeonlp setup

# Option 1a. Install Jageocoder gaiku_all_v21.zip
# ENV JAGEOCODER_DB2_DIR /opt/db2
# RUN curl https://www.info-proto.com/static/jageocoder/latest/gaiku_all_v21.zip \
#     -o /opt/gaiku_all_v21.zip && \
#     jageocoder install-dictionary /opt/gaiku_all_v21.zip && \
#     rm /opt/gaiku_all_v21.zip

# Option 1b. Use Jageocoder server
# ENV JAGEOCODER_SERVER_URL https://jageocoder.info-proto.com/jsonrpc

# Option 2. Install neologd
# ENV GEONLP_MECAB_DIC_DIR=/neologd
# RUN apt-get install -y git mecab
# RUN cd /tmp \
#     && git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git \
#     && cd mecab-ipadic-neologd \
#     && ./bin/install-mecab-ipadic-neologd --prefix /neologd -n -a -u -y
