version: "3.7"

services:
  pygeonlp:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - type: bind
        source: ./pygeonlp/api
        target: /develop/pygeonlp/api

